# примеры API-запросов
# cbd4d3f17636273ed8b77935cf5c8dd7566c53b1 - АДМИНСКИЙ ТОКЕН
# 865eb6cca3a2dc907aca40babc680dc59b550574 - ТОКЕН ПОЛЬЗОВАТЕЛЯ
###

# получение списка товаров
GET http://localhost:8000/api/v1/products/
Content-Type: application/json

###
# создание товара
POST http://localhost:8000/api/v1/products/
Content-Type: application/json
Authorization: Token cbd4d3f17636273ed8b77935cf5c8dd7566c53b1

{
  "name": "Nokia 3310",
  "description": "Старый добрый кирпич снова в деле",
  "price": 3500
}

###

# попытка поменять товар
PATCH http://localhost:8000/api/v1/products/1/
Content-Type: application/json
Authorization: Token 865eb6cca3a2dc907aca40babc680dc59b550574

{
  "name": "Шкаф IKEA",
  "description": "TEST",
  "price": 1245678
}

###

# удалить товар
DELETE http://localhost:8000/api/v1/products/1/
Content-Type: application/json
Authorization: Token 865eb6cca3a2dc907aca40babc680dc59b550574

###

# фильтрация по ценовой политике
GET http://localhost:8000/api/v1/products?min_price=2000&max_price=80000
Content-Type: application/json

###

# оставить отзыв о товаре
POST http://localhost:8000/api/v1/product-reviews/
Content-Type: application/json
Authorization: Token 865eb6cca3a2dc907aca40babc680dc59b550574

{
  "product": 2,
  "text": "Вспомнил, прослезился. Шедевр! А эта змейка... Да что она себе позволяет?!",
  "rating": 5
}
###

# получить отзывы о товарах
GET http://localhost:8000/api/v1/product-reviews/
Content-Type: application/json

###

# изменить отзыв о товаре
PATCH http://localhost:8000/api/v1/product-reviews/3/
Content-Type: application/json
Authorization: Token 865eb6cca3a2dc907aca40babc680dc59b550574

{
  "product": 1,
  "text": "Хороший смартфон, но очень дорогой.",
  "rating": 4
}

###

# удалить отзыв о товаре
DELETE http://localhost:8000/api/v1/product-reviews/1/
Content-Type: application/json
Authorization: Token e968a27e10e4d0589cbc9035625b1e84345f5d85

###

# получить заказы
GET http://localhost:8000/api/v1/orders/
Content-Type: application/json

###

# отправить заказ
POST http://localhost:8000/api/v1/orders/
Content-Type: application/json
Authorization: Token cbd4d3f17636273ed8b77935cf5c8dd7566c53b1

{
  "position_orders": [
    {
      "product_id": 1,
      "quantity": 2
    }
  ]
}
###