# примеры API-запросов
# cbd4d3f17636273ed8b77935cf5c8dd7566c53b1 - АДМИНСКИЙ ТОКЕН
# 865eb6cca3a2dc907aca40babc680dc59b550574 - ТОКЕН ПОЛЬЗОВАТЕЛЯ
###

# получение списка товаров
GET http://localhost:8000/api/v1/products/
Content-Type: application/json

###
# создание товара
POST http://localhost:8000/api/v1/products/
Content-Type: application/json
Authorization: Token cbd4d3f17636273ed8b77935cf5c8dd7566c53b1

{
  "name": "Nokia 3310",
  "description": "Старый добрый кирпич снова в деле",
  "price": 3500
}

###

# попытка поменять товар
PATCH http://localhost:8000/api/v1/products/1/
Content-Type: application/json
Authorization: Token 865eb6cca3a2dc907aca40babc680dc59b550574

{
  "name": "Шкаф IKEA",
  "description": "TEST",
  "price": 1245678
}

###

# удалить товар
DELETE http://localhost:8000/api/v1/products/1/
Content-Type: application/json
Authorization: Token 865eb6cca3a2dc907aca40babc680dc59b550574

###

# фильтрация по ценовой политике
GET http://localhost:8000/api/v1/products?min_price=2000&max_price=80000
Content-Type: application/json

###

# оставить отзыв о товаре
POST http://localhost:8000/api/v1/product-reviews/
Content-Type: application/json
Authorization: Token cbd4d3f17636273ed8b77935cf5c8dd7566c53b1

{
  "product": 2,
  "text": "Этот телефон уже такой древний, как сами знаете что!",
  "rating": 1
}
###

# получить отзывы о товарах
GET http://localhost:8000/api/v1/product-reviews/
Content-Type: application/json

###

# изменить отзыв о товаре
PATCH http://localhost:8000/api/v1/product-reviews/8/
Content-Type: application/json
Authorization: Token cbd4d3f17636273ed8b77935cf5c8dd7566c53b1

{
  "product": 2,
  "text": "Вполне себе хороший телефон.",
  "rating": 4
}

###

# удалить отзыв о товаре
DELETE http://localhost:8000/api/v1/product-reviews/8/
Content-Type: application/json
Authorization: Token cbd4d3f17636273ed8b77935cf5c8dd7566c53b1

###

# получить заказы
GET http://localhost:8000/api/v1/orders/
Content-Type: application/json
#Authorization: Token cbd4d3f17636273ed8b77935cf5c8dd7566c53b1
Authorization: Token 865eb6cca3a2dc907aca40babc680dc59b550574
###

# отправить заказ
POST http://localhost:8000/api/v1/orders/
Content-Type: application/json
Authorization: Token 865eb6cca3a2dc907aca40babc680dc59b550574

{
  "positions": [
    {
      "product_id": 2,
      "quantity": 2
    }
  ]
}
###

# удалить заказ
DELETE http://localhost:8000/api/v1/orders/65/
Content-Type: application/json
Authorization: Token 865eb6cca3a2dc907aca40babc680dc59b550574

###

# изменить статус заказа
PATCH http://localhost:8000/api/v1/orders/65/
Content-Type: application/json
Authorization: Token cbd4d3f17636273ed8b77935cf5c8dd7566c53b1
#Authorization: Token 865eb6cca3a2dc907aca40babc680dc59b550574

{
  "status": "IN_PROGRESS"
}

###
