# Generated by Django 3.1.3 on 2020-11-24 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201124_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='positions',
            new_name='position',
        ),
    ]
