# Generated by Django 3.1.3 on 2020-11-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20201125_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='position',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
