# Generated by Django 3.1.3 on 2020-11-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20201125_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='order_price',
        ),
    ]
